/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadastromariannamaria;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author silva
 */
public class NewJFrame extends javax.swing.JFrame {

    String CADASTRO[][] = new String[10][3];
    int i = 0, x = 0;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cadnome = new javax.swing.JTextField();
        cadcidade = new javax.swing.JTextField();
        jLabelcidade = new javax.swing.JLabel();
        jLabelnome = new javax.swing.JLabel();
        cadestado = new javax.swing.JTextField();
        jLabelestado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadnomeActionPerformed(evt);
            }
        });
        jPanel1.add(cadnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 220, -1));

        cadcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadcidadeActionPerformed(evt);
            }
        });
        jPanel1.add(cadcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 220, -1));

        jLabelcidade.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelcidade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcidade.setText("Cidade:");
        jPanel1.add(jLabelcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabelnome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelnome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelnome.setText("Nome completo:");
        jPanel1.add(jLabelnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        cadestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadestadoActionPerformed(evt);
            }
        });
        jPanel1.add(cadestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, -1));

        jLabelestado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelestado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelestado.setText("Estado:");
        jPanel1.add(jLabelestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setText("CADASTRAR");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 90, 30));

        jButton2.setBackground(new java.awt.Color(0, 153, 102));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton2.setText("IMPRIMIR");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastromariannamaria/e (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 436, 300));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(0, 153, 102));
        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton3.setText("INICIAR CADASTRO");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastromariannamaria/e.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, -1, 330));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadcidadeActionPerformed

    private void cadestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadestadoActionPerformed

    private void cadnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadnomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cadnome.requestFocus();
        if (cadnome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe seu nome.");
            cadnome.requestFocus();
            cadnome.setForeground(Color.red);
            jLabelnome.setForeground(Color.red);

        } else if (cadcidade.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe sua cidade.");
            cadcidade.requestFocus();
            cadcidade.setForeground(Color.red);
            jLabelcidade.setForeground(Color.red);

        } else if (cadestado.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe seu estado.");
            cadestado.requestFocus();
            cadestado.setForeground(Color.red);
            jLabelestado.setForeground(Color.red);

        } else {
            CADASTRO[i][x] = cadnome.getText();
            x++;
            CADASTRO[i][x] = cadcidade.getText();
            x++;
            CADASTRO[i][x] = cadestado.getText();
            x = 0;
            i++;
            JOptionPane.showMessageDialog(this, "Cadastramento feito!");
            cadnome.setText(null);
            cadcidade.setText(null);
            cadestado.setText(null);
            cadnome.setForeground(Color.black);
            cadnome.setForeground(Color.black);
            cadnome.setForeground(Color.black);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String todos_cadastros = "";
        for (int a = 0; a < i; a++) {
            todos_cadastros += "Nome: " + CADASTRO[a][0] + "\nCidade: " + CADASTRO[a][1] + "\nEstado: " + CADASTRO[a][2] + "\n\n";
        }
        JOptionPane.showMessageDialog(null, todos_cadastros);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cadcidade;
    private javax.swing.JTextField cadestado;
    private javax.swing.JTextField cadnome;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelcidade;
    private javax.swing.JLabel jLabelestado;
    private javax.swing.JLabel jLabelnome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
